seed: 111
cuda: 0 # use_gpu
env:
  env_type: meta
  env_name: Wind-v0
  max_rollouts_per_task: 1 # k. total steps: 25

  num_tasks: 60
  num_train_tasks: 40
  num_eval_tasks: 20

train:
  # sample complexity: BAMDP horizon * (num_init_rollouts_pool * num_train_tasks
    #  + num_iters * num_tasks_sample * num_rollouts_per_iter)
    # 1000*10*75 = 750k steps
  # rl training steps: num_iters * updates_per_iter

  num_iters: 1000 # number meta-training iterates
  num_init_rollouts_pool: 100 #  before training
  num_rollouts_per_iter: 10  # 1 #

  rl_updates_per_iter: 500 
  vae_updates_per_iter: 30 # good

  policy_batch_size: 4800 # 64*75
  vae_batch_num_rollouts: 64

  log_interval: 4 # num of iters
  save_interval: 100 # -1
  log_tensorboard: true

policy:
  buffer_size: 1e6
  # bamdp related
  sample_embeddings: false # (otherwise: pass mean) obs_dim + 2*task_dim
  switch_to_belief_reward: null # when to switch from R to R+; None is to not switch

  policy: sac
  dqn_layers: [128, 128]
  policy_layers: [128, 128]
  lr: 0.0003
  # sac alpha
  entropy_alpha: 0.01 # tend to be det policy...
  automatic_entropy_tuning: true
  alpha_lr: 0.0003

  gamma: 0.9
  tau: 0.005

vae:
  buffer_size: 1e6
  task_embedding_size: 5 # dim of latent space
  
  optim:
    vae_lr: 0.001
    rew_loss_coeff: 1.0
    state_loss_coeff: 1.0 # (vs reward loss)
    kl_weight: 0.1
    kl_to_gauss_prior: false
    train_by_batch: true # false is by split

  # encoder
  encoder:
    aggregator_hidden_size: 64
    layers_before_aggregator: []
    layers_after_aggregator: []
    action_embedding_size: 8 # has action input
    state_embedding_size: 32
    reward_embedding_size: 0 # no reward input

  decoder:
    disable_stochasticity_in_latent: false
    # decoder: reward function r(s,m)
    decode_reward: false # not used
    reward_decoder_layers: []
    rew_pred_type: deterministic # gaussian, deterministic
    input_prev_state: false
    input_action: false
    # decoder: state transition p(s'|s,a,m)
    decode_state: true
    state_decoder_layers: [64, 32]
    state_pred_type: deterministic
