seed: 7
cuda: -1 # use cpu is 15% faster
env:
  env_type: meta
  env_name: HalfCheetahVel-v0
  max_rollouts_per_task: 2 # k=2, H=200, H^+ =400

  num_tasks: 120
  num_train_tasks: 100
  num_eval_tasks: 20

train:
  # 2500*2048=5.1M steps, cost ? days
  num_iters: 2500 # number meta-training iterates

eval:
  log_interval: 10 # num of iters
  save_interval: 100 # not 
  log_tensorboard: true

policy:
  algo: ppo
