seed: 1
cuda: -1 # use_gpu
env:
  env_type: rmdp
  env_name: MRPOHalfCheetahRandomNormal-v0

train:
  # train 20M env steps, around 500 updates, 50000 episodes
  # Originally MRPO train 2000 updates
  num_iters: 20000

eval:
  log_interval: 1 # in terms of updates
  save_interval: 10 # -1
  log_tensorboard: true
